#!/usr/bin/python3

import os, pickle, re
from flask import Flask, render_template, session, request, redirect, url_for, send_from_directory, abort

# pickled source file, generated by gumtree_search_scraper.py
source_file = 'master_post_list.pak' 
# Regex cases in the description which should cause items to be excluded 
desc_fail = [ "midi|phone repair" ]
# Regex cases in the title which should cause items to be excluded 
titl_fail = [ "laptop|ipad|surface pro|casio|desk|music|macbook|yamaha|hiring|midi|audio repair|glass repair|imac|toddler|iphone|electronic keyboard|watch" ]

# Import data from pickled source
master_post_list = []
with open(source_file, 'rb') as f:
	master_post_list = pickle.load(f)
	
re_desc_fail = []
re_titl_fail = []
for d in desc_fail: re_desc_fail.append(re.compile(d, flags=re.I))
for d in titl_fail: re_titl_fail.append(re.compile(d, flags=re.I))

app = Flask(__name__)

##################

@app.route('/', methods=['GET'])
def home():

    # Create a list of items which do not pass the regex fail cases
	list = []
	for post in master_post_list:
		fail_f = False
		for rx in re_titl_fail:
			if rx.search(post['title']): fail_f = True
		for rx in re_desc_fail:
			if rx.search(post['description']): fail_f = True
			
		if fail_f: continue
		list.append(post)

	return render_template('home.html', posts=list)

##################

if __name__ == '__main__':
    app.secret_key = os.urandom(12)
    app.run(debug=True, host="0.0.0.0", port=7802)